### ISSUE TITLE
Chat join message and sending messages

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#341]
http://images.brickimedia.org/f/f9/Screen_Shot_2015-03-02_at_21.26.13.png

![image](https://cloud.githubusercontent.com/assets/4723983/6454051/a8ecdf10-c10a-11e4-9ec3-4ea9e9add162.png)

For some reason, on the other side of my friend, Crevs Daak, showed this where I joined multiple times even though I joined once. Although he fixed the problem by refreshing, he also said that he can't see his messages when he sends them.

**Comment by UltrasonicNXT** [comment]
Nice. Can I get browser details and if there are any errors in the JS console?

**Comment by codyn329** [comment]
Here's the full report I got from him alongside some extra notes: 
* Browser: Safari version 6.1.6 (7537.78.2)
* Operating system:  OSX 10.7.5
* only happens on fullscreen mode
* works alright on normal (all options under Misc->Chat unchecked)

**Comment by CrevsDaak** [comment]
Bonus picture of the day!
![screen shot 2015-03-03 at 21 05 34](https://cloud.githubusercontent.com/assets/7662343/6475498/bda67e2c-c1e9-11e4-9741-773f9607532a.png)
I'm not sure what it means but those triggered when I typed in a message and when Codyn joined.

**Comment by codyn329** [comment]
It means there was a function that was not given a value (undefined), or something close I think.

**Comment by UltrasonicNXT** [comment]
hmm something to do with fulllscreen JS loading then. This feature is rarely used, so I guess not surprising that there are bugs, but it's always worked for me. I'll have a look.

**Comment by UltrasonicNXT** [comment]
Okay, I've pushed a commit, can we see if this's fixed it?

**Comment by georgebarnick** [comment]
@UltrasonicNXT: Chat no longer appears to be autoscrolling, which confused me for a bit because I missed a lot of replies because they didn't scroll.

**Comment by CrevsDaak** [comment]
![screen shot 2015-03-07 at 23 09 21](https://cloud.githubusercontent.com/assets/7662343/6544145/080897ce-c51f-11e4-9ab3-ab3d5ce8bfe6.png)
I'm still unable to see my messages after I send, not sure about the multiple joining messages bug (I'll try tha later).

**Comment by codyn329** [comment]
crev said its been fixed :)
